### PR TITLE
Changed ui for the web interface

### PR DESCRIPTION
**Pull request by Yaswanth14**
image

### CODE REVIEW

**Comment by Raghucharan16** [comment]
Thanks for the PR :) But I need to update the revanced.yml to push the 3 apk names properly. now it is taking only 2. can you take a look at that one?

**Review by Raghucharan16 — APPROVED** [review]
This is fine. need some changes for future changes.

**Comment by Raghucharan16** [comment]
hey @Yaswanth14 i have made some changes, and in interface we are getting search bar which is not needed for now. and also it is not functional in my code atleast. could you check that? 
thanks:).

**Comment by Yaswanth14** [comment]
I'll change the UI. Search bar is not functional just added as it might be needed in the future, I will remove that

**Pull request closed without merging**
